### ISSUE TITLE
Failure of load mesh asset

### ISSUE THREAD

**Issue by pengjunkun** [MorningFrog/urdf-visualizer#1]
Hi Wenyao,
Thanks for your exciting work!
I really think this values.

There is a tiny obstacle blocking me, hope you may help fix it.

REPEAT WAY:
1. Environment
     Devcontainer(Ubuntu 20.04)
2. Code
https://github.com/leap-hand/LEAP_Hand_Sim/blob/master/assets/leap_hand/robot.urdf

Error reporting:
"Failed to load https://file%2B.vscode-resource.vscode-cdn.net/workspaces/LEAP_Hand_Sim_hi/assets/leap_hand/palm_lower.stl"

My email is: pengjunkun_at_gmail.com, focusing on Dexterous hand research, if you want more academic/engineering exchange.
Thanks again!

Junkun

**Comment by MorningFrog** [comment]
Hi Junkun,
Thanks for your feedback.
I have tried it and find the problem. I will fix it in the next version! You can install the 2.0.2 version of the extension, it doesn't have this problem.
Thanks again!
![dexterous hand](https://github.com/user-attachments/assets/4b69311f-63a9-44d2-9ac3-719a1aec6e1c)

**Comment by MorningFrog** [comment]
Remember to open your vscode in the folder of the project, not open the file only.

**Comment by MorningFrog** [comment]
I have solved the problem in Windows system in version 2.0.4. The problem have not happened in Ubuntu. You might open VSCode only with the urdf file, please open VSCode in the project folder.
Thanks!
