### ISSUE TITLE
Failure of load mesh asset in Devcontainer

### ISSUE THREAD

**Issue by pengjunkun** [MorningFrog/urdf-visualizer#2]
Hi Wenyao,
Thanks for your timely response.
I may not explain the issue clearly, especially about its running environment ([Vscode Devcontainer](https://code.visualstudio.com/docs/devcontainers/containers)).

# Works well through directly open
I have tried again in normal env (directly open the folder in vscode), and it works well, as below.
![image](https://github.com/user-attachments/assets/92b7240c-a6c2-461e-a127-cdb506edf646)

# NOT work in Devcontainer
![image](https://github.com/user-attachments/assets/5d73d47c-75b3-40b8-83fc-d42933bf3048)
REPEAT WAY:
Environment
[Vscode Devcontainer](https://code.visualstudio.com/docs/devcontainers/containers)(Ubuntu 20.04)
Code
https://github.com/leap-hand/LEAP_Hand_Sim/blob/master/assets/leap_hand/robot.urdf
Error reporting:
"Failed to load [https://file%2B.vscode-resource.vscode-cdn.net/workspaces/LEAP_Hand_Sim_hi/assets/leap_hand/palm_lower.stl](https://file+.vscode-resource.vscode-cdn.net/workspaces/LEAP_Hand_Sim_hi/assets/leap_hand/palm_lower.stl)"

Thanks again!

Junkun

**Comment by MorningFrog** [comment]
Hi Junkun,
Thank you for providing a detailed explanation of the issue. I have fixed this bug in version 2.0.5, you can install it in VSCode.
Thank you very much for your participation.
![image](https://github.com/user-attachments/assets/3cc0e0f7-46b8-43b3-86f0-67985d7aca52)
Wenyao Ma

**Comment by pengjunkun** [comment]
Hi Wenyao,
Yes, it works very well!

Thanks.

Junkun
