### ISSUE TITLE
Failure to open a URDF model

### ISSUE THREAD

**Issue by LoreMoretti** [MorningFrog/urdf-visualizer#3]
When trying to open a urdf model, I am getting the following error:

![image](https://github.com/user-attachments/assets/5a2f4784-1c31-42b5-9f3e-d8a8d9a52e30)

The urdf model I want to visualize is: https://github.com/icub-tech-iit/ergocub-software/blob/master/urdf/ergoCub/robots/ergoCubGazeboV1_1/model.urdf

I have opened vscode from this folder: https://github.com/icub-tech-iit/ergocub-software/tree/master/urdf

I have set the following settings:

```
 {
     "urdf-visualizer.packages": {
          // other settings
          "urdf-visualizer.packages": {
            "ergoCub": "${workspaceFolder}"
        },        
     }
}

```

**Comment by MorningFrog** [comment]
Please ensure that URDF file is recognized as XML format in VSCode (please provide a screenshot of VSCode to help me identify the issue).
When writing `.vscode/settings.json`, there seems to be a problem, the correct one should be similar to the following:
```
 {
  "urdf-visualizer.packages": {
    "ergoCub": "${workspaceFolder}/ergoCub"
  }
}
```

**Comment by MorningFrog** [comment]
I have opened this model here, you can click on the "urdf" in the bottom right corner and check if there has "xml" tag.

https://github.com/user-attachments/assets/fccce9cb-df42-4a24-bed7-8bd2d46f9f43
